# Generated by Django 6.0.6 on 2026-07-03 13:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_user_register', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Users',
            new_name='User',
        ),
    ]
